version: "3"
services:
  postgres:
    image: postgres
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - tracking
    ports:
      - "5432:5432"
      

  test-gps:
    image: marouanelhamidi/test-gps
    container_name: map_tracking-back
    environment:
      - POSTGRESQL_DB=postgres
    networks:
      - tracking
    ports:
      - "8080:8080"
    depends_on:
      - postgres





networks:
  tracking:


